interface CADModel {
  script: string;
  format: 'STL' | 'STEP' | 'OBJ' | 'OpenSCAD' | 'DXF' | 'IGES';
  metadata: {
    modelName: string;
    description: string;
    units: string;
    timestamp: string;
  };
}

class CADDownloadManager {
  /**
   * Download CAD model file
   */
  downloadCAD(model: CADModel): void {
    const { script, format, metadata } = model;
    
    // Sanitize filename
    const filename = this.generateFilename(metadata.modelName, format);
    
    // Generate file content based on format
    let content: string;
    let mimeType: string;

    switch (format) {
      case 'STL':
        content = this.ensureSTLFormat(script);
        mimeType = 'model/stl';
        break;
      
      case 'OpenSCAD':
        content = this.formatOpenSCAD(script, metadata);
        mimeType = 'text/plain';
        break;
      
      case 'OBJ':
        content = this.ensureOBJFormat(script);
        mimeType = 'model/obj';
        break;
      
      case 'STEP':
        content = this.formatSTEP(script, metadata);
        mimeType = 'application/step';
        break;
      
      case 'DXF':
        content = this.formatDXF(script, metadata);
        mimeType = 'application/dxf';
        break;
      
      case 'IGES':
        content = this.formatIGES(script, metadata);
        mimeType = 'application/iges';
        break;
      
      default:
        content = script;
        mimeType = 'text/plain';
    }

    // Add metadata header
    const fullContent = this.addMetadataHeader(content, metadata, format);
    
    // Trigger download
    this.triggerDownload(fullContent, filename, mimeType);
    
    // Log download
    console.log(`✅ Downloaded: ${filename}`);
  }

  /**
   * Download as ZIP archive with multiple formats
   */
  downloadMultiFormat(model: CADModel, formats: string[]): void {
    console.log(`📦 Preparing multi-format download for ${formats.length} formats...`);
    
    // For now, downloads individually
    formats.forEach(format => {
      setTimeout(() => {
        this.downloadCAD({
          ...model,
          format: format as any
        });
      }, 100); // Small delay between downloads
    });
  }

  /**
   * Generate standardized filename
   */
  private generateFilename(modelName: string, format: string): string {
    // Sanitize model name
    const sanitized = modelName
      .replace(/[^a-z0-9]/gi, '_')
      .toLowerCase()
      .substring(0, 50);
    
    // Add timestamp
    const timestamp = new Date().toISOString().split('T')[0];
    
    // Get file extension
    const extension = this.getFileExtension(format);
    
    return `${sanitized}_${timestamp}.${extension}`;
  }

  private getFileExtension(format: string): string {
    const extensions: Record<string, string> = {
      'STL': 'stl',
      'OpenSCAD': 'scad',
      'OBJ': 'obj',
      'STEP': 'step',
      'DXF': 'dxf',
      'IGES': 'igs'
    };
    return extensions[format] || 'txt';
  }

  /**
   * Ensure STL format is correct
   */
  private ensureSTLFormat(content: string): string {
    // Check if already in STL format
    if (content.trim().startsWith('solid') || content.includes('facet normal')) {
      return content;
    }
    
    // If not, it might be binary or needs conversion
    return content;
  }

  /**
   * Format as OpenSCAD with proper syntax
   */
  private formatOpenSCAD(script: string, metadata: any): string {
    // Add OpenSCAD header comments
    let formatted = `// OpenSCAD Model\n`;
    formatted += `// Generated by Kelmoid AI Genesis\n`;
    formatted += `// Model: ${metadata.modelName}\n`;
    formatted += `// Description: ${metadata.description}\n`;
    formatted += `// Units: ${metadata.units}\n`;
    formatted += `// Date: ${metadata.timestamp}\n`;
    formatted += `\n`;
    formatted += script;
    
    return formatted;
  }

  /**
   * Ensure OBJ format
   */
  private ensureOBJFormat(content: string): string {
    if (content.trim().startsWith('v ') || content.includes('vn ')) {
      return content;
    }
    return content;
  }

  /**
   * Format STEP file (ISO 10303-21)
   */
  private formatSTEP(script: string, metadata: any): string {
    // Basic STEP wrapper
    let step = `ISO-10303-21;\n`;
    step += `HEADER;\n`;
    step += `FILE_DESCRIPTION(('Kelmoid AI Generated Model'),'2;1');\n`;
    step += `FILE_NAME('${metadata.modelName}','${metadata.timestamp}',('Kelmoid AI'),('Kelmoid Genesis'),'','','');\n`;
    step += `FILE_SCHEMA(('AUTOMOTIVE_DESIGN'));\n`;
    step += `ENDSEC;\n`;
    step += `DATA;\n`;
    step += script;
    step += `\nENDSEC;\n`;
    step += `END-ISO-10303-21;\n`;
    
    return step;
  }

  /**
   * Format DXF file (Drawing Exchange Format)
   */
  private formatDXF(script: string, metadata: any): string {
    // Basic DXF wrapper
    let dxf = `  0\nSECTION\n  2\nHEADER\n`;
    dxf += `  9\n$ACADVER\n  1\nAC1015\n`;
    dxf += `  0\nENDSEC\n`;
    dxf += `  0\nSECTION\n  2\nENTITIES\n`;
    dxf += script;
    dxf += `  0\nENDSEC\n`;
    dxf += `  0\nEOF\n`;
    
    return dxf;
  }

  /**
   * Format IGES file (Initial Graphics Exchange Specification)
   */
  private formatIGES(script: string, metadata: any): string {
    // Basic IGES wrapper
    let iges = `                                                                        S      1\n`;
    iges += `1H,,1H;,7HKelmoid,16HAI Genesis Model,32,38,6,308,15,7HKelmoid,1.,2,     G      1\n`;
    iges += `2HMM,1,0.01,15H${metadata.timestamp},1.E-06,0.,,,11,0,                  G      2\n`;
    iges += `15H${metadata.timestamp},;                                              G      3\n`;
    iges += script;
    iges += `S      1G      3D      0P      0                                        T      1\n`;
    
    return iges;
  }

  /**
   * Add metadata header to file
   */
  private addMetadataHeader(content: string, metadata: any, format: string): string {
    // For text formats, add comment header
    if (['OpenSCAD', 'OBJ', 'DXF'].includes(format)) {
      const commentChar = format === 'DXF' ? '999' : '//';
      let header = `${commentChar} ================================================\n`;
      header += `${commentChar} Kelmoid AI Genesis - Generated CAD Model\n`;
      header += `${commentChar} ================================================\n`;
      header += `${commentChar} Model Name: ${metadata.modelName}\n`;
      header += `${commentChar} Description: ${metadata.description}\n`;
      header += `${commentChar} Format: ${format}\n`;
      header += `${commentChar} Units: ${metadata.units}\n`;
      header += `${commentChar} Generated: ${metadata.timestamp}\n`;
      header += `${commentChar} ================================================\n\n`;
      return header + content;
    }
    
    return content;
  }

  /**
   * Trigger browser download
   */
  private triggerDownload(content: string, filename: string, mimeType: string): void {
    // Create blob
    const blob = new Blob([content], { type: mimeType });
    
    // Create download link
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.style.display = 'none';
    
    // Trigger download
    document.body.appendChild(link);
    link.click();
    
    // Cleanup
    setTimeout(() => {
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, 100);
  }

  /**
   * Download with custom filename
   */
  downloadWithCustomName(
    model: CADModel, 
    customFilename: string
  ): void {
    const extension = this.getFileExtension(model.format);
    const filename = customFilename.endsWith(`.${extension}`) 
      ? customFilename 
      : `${customFilename}.${extension}`;
    
    const content = model.script;
    const mimeType = this.getMimeType(model.format);
    
    this.triggerDownload(content, filename, mimeType);
  }

  private getMimeType(format: string): string {
    const mimeTypes: Record<string, string> = {
      'STL': 'model/stl',
      'OpenSCAD': 'text/plain',
      'OBJ': 'model/obj',
      'STEP': 'application/step',
      'DXF': 'application/dxf',
      'IGES': 'application/iges'
    };
    return mimeTypes[format] || 'text/plain';
  }

  /**
   * Get download statistics
   */
  getDownloadInfo(model: CADModel): {
    filename: string;
    size: string;
    format: string;
  } {
    const filename = this.generateFilename(model.metadata.modelName, model.format);
    const sizeBytes = new Blob([model.script]).size;
    const sizeKB = (sizeBytes / 1024).toFixed(2);
    
    return {
      filename,
      size: `${sizeKB} KB`,
      format: model.format
    };
  }

  /**
   * Validate CAD content before download
   */
  validateCAD(model: CADModel): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    
    // Check if content exists
    if (!model.script || model.script.trim().length === 0) {
      errors.push('CAD script is empty');
    }
    
    // Format-specific validation
    switch (model.format) {
      case 'STL':
        if (!model.script.includes('facet') && !model.script.includes('vertex')) {
          errors.push('Invalid STL format - missing geometric data');
        }
        break;
      
      case 'OpenSCAD':
        if (!model.script.includes('module') && 
            !model.script.includes('cube') && 
            !model.script.includes('cylinder') &&
            !model.script.includes('sphere')) {
          errors.push('Invalid OpenSCAD format - no geometric primitives found');
        }
        break;
    }
    
    return {
      valid: errors.length === 0,
      errors
    };
  }
}

export { CADDownloadManager, type CADModel };